### ISSUE TITLE
[Enhancement] Show only by button

### ISSUE THREAD

**Issue by seiya-git** [gomita/verticaltoolbar#35]
Please add this option

**Comment by dustyv** [comment]
This option is already there:
Viz: Vertical toolbar options -> Buttons -> Icons
![vt](https://cloud.githubusercontent.com/assets/6603564/6365993/2c73f9fc-bcb7-11e4-92e0-861505e8a5e5.png)

Hope this helps

**Comment by seiya-git** [comment]
no, it's different.
not show vtb by hover, only clicking on 'always show vtb'

**Comment by dustyv** [comment]
I'm not sure I quite understand your issue.
Are you trying to 'hide' VTB - in which case (see picture in my reply above) where it says 'Normal' change to "Automatically Hide", then running the cursor (in my case) to the left side of the screen - VTB re-appears.
Or perhaps is there something else you are trying to achieve?

**Comment by seiya-git** [comment]
when running the cursor (for example) to the left side of the screen - VTB don't appears.
only by clicking "always show" button will be appear.
![button](http://ipic.su/img/img7/fs/kiss_8kb.1424890140.png)

**Comment by dustyv** [comment]
Are you using Firefox?
Are you using VTB 1.08 (the latest)?
I have recreated from your text, but my version works perfectly.
Last resort: I suggest you remove VTB, restart browser, re-install.
Please let me know how you get on.
Thanks

**Comment by seiya-git** [comment]
Latest... I just want option for don't show VTB on mousehover

**Comment by dustyv** [comment]
Right, I see what it is you want.
Can't help there I'm afraid.
Bye for now - and Thanks.
