### ISSUE TITLE
Firefox 41 Youtube full screen mode

### ISSUE THREAD

**Issue by strawbeard** [gomita/verticaltoolbar#39]
After having upgraded Firefox 38.0.2 to 41.0 hiding (and un-hiding) VT (1.0.9.1) in full screen mode (Youtube) doesn't work properly. Options are set to Normal: Always show and Full Screen: Never show.

When I switch a video to full screen mode, VT remains visible but disappears when I return to normal mode. Switching to other tabs doesn't bring VT back. I can only make it visible again by invoking the VT options dialog and pressing Done.

This may very well be a Firefox issue; I didn't find anything on Bugzilla yet (but I'm quite bad at finding things there;-)

**Comment by gomita** [comment]
Confirmed.

**Comment by strawbeard** [comment]
Really fast move! Thank you very much!
