### ISSUE TITLE
not working on latest Firefox

### ISSUE THREAD

**Issue by hamadeguchi** [gomita/verticaltoolbar#45]
same problem is reported on mozilla site. 
https://addons.mozilla.org/ja/firefox/addon/vertical-toolbar/

**Comment by gomita** [comment]
The xpi file of ver.1.0.14 is corrupt.
Please update to ver.1.0.15.

**Comment by hamadeguchi** [comment]
worked fine!
thank you for your quick response.

Great Addon!
